### ISSUE TITLE
Access Issues for Dataset Download

### ISSUE THREAD

**Issue by serdaryildiz** [hwz-zju/Instruct-ReID#10]
Thanks for your awesome works!

I am eager to reproduce the results of the Instruct-ReID but am unfortunately unable to access the dataset through the provided Baidu links. Could you kindly provide alternative download links or suggest another method for obtaining the datasets?

**Comment by hwz-zju** [comment]
Hello! thank you for your attention to our work. We provide our annotations by Google Drive link not through the Baidu links. Due to copyright reasons, we are unable to provide image data. However, we have provided homepage links for these datasets where you can obtain the original image data from owners.

**Comment by serdaryildiz** [comment]
Thank you for the quick response. I understand that the original image data needs to be obtained directly from the dataset owners. However, I am located outside of China and am having difficulty accessing the Baidu links for the image data. Is there any way to access these dataset images?
